name: Build (Windows x64)

on:
  push:
    branches:
      - master
      - merge/dalkon_2
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    
    - name: Boost - Build
      uses: MarkusJx/install-boost@v2.4.1
      id: install-boost
      with:
          boost_version: 1.73.0
          boost_install_dir: ${{runner.temp}}\boost_tmp
          platform_version: 2019

    - name: Boost - Install
      run: |
        rm -r "${{runner.workspace}}\recap_server\darkspore_server\libs\boost_1_73_0"
        mv "${{runner.temp}}\boost_tmp\boost\boost" "${{runner.workspace}}\recap_server\darkspore_server\libs\boost_1_73_0"

    # - name: LuaJIT - Build
    #   working-directory: ${{runner.workspace}}\recap_server\darkspore_server\libs\LuaJIT
    #   run: make install

    # - name: LuaJIT - Test
    #   working-directory: ${{runner.workspace}}\recap_server\darkspore_server\libs\LuaJIT
    #   run: ls

    - name: Check available Windows SDKs
      id: check_sdks
      run: |
        set -x
        echo "Checking available Windows SDKs..."
        echo
        setup-msbuild list-sdks
        
    - name: Build Recap Server
      run: msbuild darkspore_server.sln /p:Configuration=Release /p:Platform=x64 /p:useenv=true

    - uses: actions/upload-artifact@v1
      with:
        name: recap-server-windows-x64
        path: ${{runner.workspace}}\recap_server\darkspore_server\build