name: Build (Windows x64)

on:
  push:
    branches:
      - master
      - merge/dalkon_2
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build_and_test:
    runs-on: windows-latest
    name: Build and Test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3
        with:
          submodules: recursive
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Run MSBuild
        id: run_msbuild
        working-directory: ${{ github.workspace }}
        run: msbuild .\darkspore_server.sln /p:Configuration=Release /p:Platform=x64 /p:useenv=true
        
      - uses: actions/upload-artifact@v1
        with:
          name: recap-server-windows-x64
          path: ${{runner.workspace}}\recap_server\darkspore_server\build